# Stick                                                                        #
# Copyright (c) 2018 Jeron Aldaron Lau <jeron.lau@plopgrizzly.com>             #
# Licensed under the MIT LICENSE                                               #
#                             _        _                                       #
#                            /@\——————/@\                                      #
# .———  .                   |   o    o   |     .————      .            .       #
# |   | |  .———   .———   .——.     []     .——.  |      .——    ———: ———: | .   . #
# |   | |  |   |  |   |  \   \   <##>   /   /  |      |   |    /    /  | |   | #
# |———  |  |   |  |   |   |   ¯        ¯   |   |   -- |   |   /    /   |  \ /  #
# |     |  |   |  |———    |                |   |    | |   |  /    /    |   |   #
# |     |   ———   |       |                |    ————  |   | :——— :———  |   |   #
#                 |        \              /                              __/   #
#                           ¯————————————¯                                     #
# Cargo.toml                                                                   #

################################################################################

[package]
name = "stick"
version = "0.3.0"
authors = [
	"Jeron Aldaron Lau <jeron.lau@plopgrizzly.com>"
]

################################################################################

license = "MIT"
documentation = "https://docs.rs/stick"
homepage = "http://plopgrizzly.com/stick"
repository = "https://github.com/plopgrizzly/stick"

################################################################################

readme = "README.md"
description = """
    A platform-agnostic joystick / gamepad / controller library for Rust.
"""
keywords = [
	"interface", "joystick", "gamepad", "platform-agnostic", "controller"
]
categories = ["hardware-support"]

################################################################################

exclude = [
	"examples/*", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md", ".gitignore",
	"_config.yml", "ISSUE_TEMPLATE.md", "icon.png", "icon.ico"
]

################################################################################

[dependencies]

################################################################################
