name = "PDP Wired Xbox 360 Gamepad"
type = "xbox"

[remap]
HatUp = "Up"
HatDown = "Down"
HatLeft = "Left"
HatRight = "Right"
ActionV = "ActionH"
ActionH = "ActionV"
TriggerL = {}
TriggerR = {}
JoyX = { event = "JoyX", deadzone = 0.07 }
JoyY = { event = "JoyY", deadzone = 0.07 }
CamX = { event = "CamX", deadzone = 0.07 }
CamY = { event = "CamY", deadzone = 0.07 }
JoyZ = { event = "TriggerL", unsigned = 255 }
CamZ = { event = "TriggerR", unsigned = 255 }
