name = "Shanwan PlayStation3 Gamepad"
type = "playstation"

[remap]
ActionA = "ActionB"
ActionB = "ActionA"
ActionH = "ActionV"
ActionV = "ActionH"
TriggerL = {}
TriggerR = {}
JoyZ = { event = "TriggerL", unsigned = 255 }
CamZ = { event = "TriggerR", unsigned = 255 }
