name = "Microsoft Xbox One Controller"
type = "xbox"

[remap]
HatUp = "Up"
HatDown = "Down"
HatLeft = "Left"
HatRight = "Right"
JoyZ = { event = "TriggerL", unsigned = 255 }
CamZ = { event = "TriggerR", unsigned = 255 }
1 = "MenuL"
4 = "Joy"
5 = "Cam"
MenuL = "Exit"
