name = "Wii Remote - Mayflash Adapter"
type = "nintendo"

[remap]
HatUp = "Up"
HatDown = "Down"
HatLeft = "Left"
HatRight = "Right"
Trigger = "ActionB"
Thumb = "ActionA"
Thumb2 = "ActionV"
Top = "ActionH"
0 = "BumperL"
1 = "BumperR"
2 = "MenuL"
3 = "MenuR"
4 = "Exit"
JoyZ = "CamX"
CamX = "CamY"
CamY = "TriggerL"
CamZ = "TriggerR"
