name = "Thrustmaster Warthog Throttle"
type = "flight"

[remap]
Throttle = "Slew"
Trigger = "MousePush"
Thumb = "MicPush"
Thumb2 = "MicUp"
Top = "MicLeft"
Top2 = "MicDown"
Pinky = "MicRight"
1 = "SpeedbrakeForward"
2 = "SpeedbrakeBackward"
3 = "BoatForward"
4 = "BoatBackward"
5 = "ChinaForward"
6 = "ChinaBackward"
7 = "PinkyForward"
8 = "PinkyBackward"
9 = "ThrottleButtonL"
10 = "EngineFuelFlowL"
11 = "EngineFuelFlowR"
12 = "EngineLMotor"
13 = "EngineRMotor"
14 = "Apu"
15 = "LandingGearSilence"
16 = "FlapsUp"
17 = "FlapsDown"
18 = "Eac"
19 = "RadarAltimeter"
20 = "AutopilotToggle"
21 = "AutopilotPath"
22 = "AutopilotAlt"
25 = "EngineLIgnition"
26 = "EngineRIgnition"
JoyX = { event = "MouseX", min = 0, max = 1024 }
JoyY = { event = "MouseY", min = 0, max = 1024 }
JoyZ = { event = "ThrottleR", min = 0, max = -16339 }
CamZ = { event = "ThrottleL", min = 0, max = -16339 }
