name = "Logitech Dual Action PlayStation Gamepad"
type = "playstation"

[remap]
Trigger = "ActionH"
Thumb = "ActionA"
Thumb2 = "ActionB"
Top = "ActionV"
Top2 = "BumperL"
Pinky = "BumperR"
0 = "TriggerL"
1 = "TriggerR"
2 = "MenuL"
3 = "MenuR"
4 = "Joy"
5 = "Cam"
ActionA = "ActionH"
ActionB = "ActionA"
MenuL = "Joy"
MenuR = "Cam"
JoyZ = "CamX"
CamX = "CamY"
CamZ = { event = "CamX", scale = 0.67 }
HatUp = "Up"
HatDown = "Down"
HatLeft = "Left"
HatRight = "Right"
