name = "USB Gamepad1"
type = "Unknown"

[[button]]
code = 1
event = "ActionB"

[[button]]
code = 2
event = "ActionA"

[[button]]
code = 8
event = "Prev"

[[button]]
code = 9
event = "Next"

[[three_way]]
code = 0
neg = "DpadDown"
pos = "DpadDown"

[[three_way]]
code = 1
neg = "DpadLeft"
pos = "DpadLeft"

[[three_way]]
code = 2
neg = "DpadRight"
pos = "DpadRight"

[[three_way]]
code = 4
neg = "DpadUp"
pos = "DpadUp"
