name = "raphnet.net 4nes4snes v1.5"
type = "Unknown"

[[button]]
code = 0
event = "ActionA"

[[button]]
code = 1
event = "ActionH"

[[button]]
code = 2
event = "Prev"

[[button]]
code = 3
event = "Next"

[[button]]
code = 5
event = "ActionV"

[[button]]
code = 6
event = "BumperL"

[[button]]
code = 4
event = "ActionB"

[[button]]
code = 7
event = "BumperR"

[[axis]]
code = 1
event = "JoyY"

[[axis]]
code = 0
event = "JoyX"
