name = 'Miroof'
type = 'Unknown'

[[button]]
code = 0
event = 'ActionB'

[[button]]
code = 1
event = 'ActionA'

[[button]]
code = 2
event = 'ActionV'

[[button]]
code = 3
event = 'ActionH'

[[button]]
code = 4
event = 'BumperL'

[[button]]
code = 5
event = 'BumperR'

[[button]]
code = 6
event = 'Prev'

[[button]]
code = 7
event = 'Next'

[[axis]]
code = 0
event = 'JoyX'

[[axis]]
code = 1
event = 'JoyY'
