name = "USB Gamepad1"
type = "Unknown"

[[button]]
code = 8
event = "Prev"

[[button]]
code = 1
event = "ActionB"

[[button]]
code = 9
event = "Next"

[[button]]
code = 2
event = "ActionA"

[[three_way]]
code = 4
pos = "DpadUp"
neg = "DpadUp"

[[three_way]]
code = 1
pos = "DpadLeft"
neg = "DpadLeft"

[[three_way]]
code = 0
pos = "DpadDown"
neg = "DpadDown"

[[three_way]]
code = 2
pos = "DpadRight"
neg = "DpadRight"
