name = "Thrustmaster Flightstick"
type = "Flight"

[[button]]
code = 0
event = "TriggerR"

[[button]]
code = 1
event = "ActionA"

[[button]]
code = 2
event = "BumperR"

[[button]]
code = 3
event = "ActionB"

[[axis]]
code = 0
event = "JoyX"

[[axis]]
code = 1
event = "JoyY"

[[axis]]
code = 2
event = "Throttle"

[[three_way]]
code = 16
neg = "PovLeft"
pos = "PovRight"

[[three_way]]
code = 17
neg = "PovUp"
pos = "PovDown"
