name = 'Saitek Saitek P150'
type = 'Unknown'

[[button]]
code = 0
event = 'ActionA'

[[button]]
code = 1
event = 'ActionB'

[[button]]
code = 2
event = 'BumperR'

[[button]]
code = 3
event = 'ActionH'

[[button]]
code = 4
event = 'ActionV'

[[button]]
code = 5
event = 'TriggerR'

[[button]]
code = 6
event = 'TriggerL'

[[button]]
code = 7
event = 'BumperL'

[[three_way]]
code = 0
neg = 'DpadLeft'
pos = 'DpadRight'

[[three_way]]
code = 1
neg = 'DpadUp'
pos = 'DpadDown'
