name = 'IMS PCU#0 Gamepad Interface'
type = 'Unknown'

[[button]]
code = 0
event = 'ActionB'

[[button]]
code = 1
event = 'ActionA'

[[button]]
code = 2
event = 'ActionV'

[[button]]
code = 3
event = 'ActionH'

[[button]]
code = 4
event = 'Prev'

[[button]]
code = 5
event = 'Next'

[[three_way]]
code = 0
neg = 'DpadLeft'
pos = 'DpadRight'

[[three_way]]
code = 1
neg = 'DpadUp'
pos = 'DpadDown'
