name = 'Logitech Logitech Extreme 3D'
type = 'Unknown'

[[button]]
code = 0
event = 'ActionA'

[[button]]
code = 2
event = 'ActionH'

[[button]]
code = 4
event = 'ActionB'

[[button]]
code = 5
event = 'ActionV'

[[button]]
code = 6
event = 'Prev'

[[button]]
code = 7
event = 'Next'

[[button]]
code = 8
event = 'Home'

[[button]]
code = 9
event = 'BumperL'

[[button]]
code = 10
event = 'BumperR'

[[axis]]
code = 0
event = 'JoyX'

[[axis]]
code = 1
event = 'JoyY'

[[three_way]]
code = 16
neg = 'JoyPush'
pos = 'CamPush'
