name = 'Shanwan PlayStation3 Gamepad'
type = 'PlayStation'

[[button]]
code = 16
event = 'ActionB'

[[button]]
code = 17
event = 'ActionA'

[[button]]
code = 19
event = 'ActionV'

[[button]]
code = 20
event = 'ActionH'

[[button]]
code = 22
event = 'BumperL'

[[button]]
code = 23
event = 'BumperR'

[[button]]
code = 24
event = 'Nil'

[[button]]
code = 25
event = 'Nil'

[[button]]
code = 26
event = 'Prev'

[[button]]
code = 27
event = 'Next'

[[button]]
code = 28
event = 'Home'

[[button]]
code = 29
event = 'JoyPush'

[[button]]
code = 30
event = 'CamPush'

[[button]]
code = 256
event = 'DpadUp'

[[button]]
code = 257
event = 'DpadDown'

[[button]]
code = 258
event = 'DpadLeft'

[[button]]
code = 259
event = 'DpadRight'

[[axis]]
code = 0
event = 'JoyX'

[[axis]]
code = 1
event = 'JoyY'

[[axis]]
code = 3
event = 'CamX'

[[axis]]
code = 4
event = 'CamY'

[[trigger]]
code = 2
event = 'TriggerL'

[[trigger]]
code = 5
event = 'TriggerR'
