name = "PDP Wired Gamepad for Xbox 360"
type = "XBox"

deadzone = 0.070

[[button]]
code = 16
event = "ActionA"

[[button]]
code = 17
event = "ActionB"

[[button]]
code = 19
event = "ActionH"

[[button]]
code = 20
event = "ActionV"

[[button]]
code = 22
event = "BumperL"

[[button]]
code = 23
event = "BumperR"

[[button]]
code = 24
event = "TriggerL"

[[button]]
code = 25
event = "TriggerR"

[[button]]
code = 26
event = "Prev"

[[button]]
code = 27
event = "Next"

[[button]]
code = 28
event = "Home"

[[button]]
code = 29
event = "JoyPush"

[[button]]
code = 30
event = "PovPush"

[[axis]]
code = 1
event = "JoyY"

[[axis]]
code = 0
event = "JoyX"

[[axis]]
code = 4
event = "PovY"

[[axis]]
code = 3
event = "PovX"

[[trigger]]
code = 2
event = "TriggerL"

[[trigger]]
code = 5
event = "TriggerR"

[[three_way]]
code = 16
neg = "DpadLeft"
pos = "DpadRight"

[[three_way]]
code = 17
neg = "DpadUp"
pos = "DpadDown"
