name = '8BitDo M30 Gamepad'
type = 'NES'

[[button]]
code = 0
event = 'ActionA'

[[button]]
code = 1
event = 'ActionB'

[[button]]
code = 2
event = 'Home'

[[button]]
code = 3
event = 'ActionH'

[[button]]
code = 4
event = 'ActionV'

[[button]]
code = 6
event = 'BumperL'

[[button]]
code = 7
event = 'BumperR'

[[button]]
code = 10
event = 'Prev'

[[button]]
code = 11
event = 'Next'

[[axis]]
code = 0
event = 'JoyX'

[[axis]]
code = 1
event = 'JoyY'

[[trigger]]
code = 4
event = 'TriggerL'

[[trigger]]
code = 5
event = 'TriggerR'
