name = 'HitBox (PS3/PC) Analog Mode'
type = 'Unknown'

[[button]]
code = 0
event = 'ActionH'

[[button]]
code = 1
event = 'ActionA'

[[button]]
code = 2
event = 'ActionB'

[[button]]
code = 3
event = 'ActionV'

[[button]]
code = 4
event = 'BumperL'

[[button]]
code = 5
event = 'BumperR'

[[button]]
code = 6
event = 'TriggerL'

[[button]]
code = 7
event = 'TriggerR'

[[button]]
code = 8
event = 'Prev'

[[button]]
code = 9
event = 'Home'

[[button]]
code = 12
event = 'Next'

[[axis]]
code = 0
event = 'JoyX'

[[axis]]
code = 1
event = 'JoyY'
