name = "Suncom SFX Plus for USB"
type = "Unknown"

[[button]]
code = 0
event = "ActionA"

[[button]]
code = 1
event = "ActionH"

[[button]]
code = 2
event = "ActionB"

[[button]]
code = 3
event = "ActionV"

[[button]]
code = 4
event = "TriggerL"

[[button]]
code = 5
event = "TriggerR"

[[button]]
code = 6
event = "BumperL"

[[button]]
code = 7
event = "Prev"

[[button]]
code = 8
event = "Next"

[[button]]
code = 9
event = "BumperR"

[[axis]]
code = 0
event = "JoyX"

[[axis]]
code = 1
event = "JoyY"
