name = "Thrustmaster Flightstick"
type = "Flight"

[[button]]
code = 0 # Trigger
event = "ActionA"

[[button]]
code = 1 # Center, Lower Button
event = "ActionV"

[[button]]
code = 2 # Right Button
event = "ActionB"

[[button]]
code = 3 # Left Button
event = "ActionH"

[[axis]]
code = 0
event = "JoyX"

[[axis]]
code = 1
event = "JoyY"

[[axis]]
code = 2
event = "Throttle"
max = -1.0

[[three_way]]
code = 16
neg = "PovLeft"
pos = "PovRight"

[[three_way]]
code = 17
neg = "PovUp"
pos = "PovDown"
