name = '8BitDo NES30 Gamepad'
type = 'NES'

[[button]]
code = 0
event = 'ActionA'

[[button]]
code = 1
event = 'ActionB'

[[button]]
code = 3
event = 'ActionV'

[[button]]
code = 4
event = 'ActionH'

[[button]]
code = 6
event = 'BumperL'

[[button]]
code = 7
event = 'BumperR'

[[button]]
code = 10
event = 'Prev'

[[button]]
code = 11
event = 'Next'

[[three_way]]
code = 0
neg = 'DpadLeft'
pos = 'DpadRight'

[[three_way]]
code = 1
neg = 'DpadUp'
pos = 'DpadDown'
