name = 'Raphnet Technologies GC/N64 to USB v3.6'
type = 'Unknown'

[[button]]
code = 0
event = 'ActionA'

[[button]]
code = 1
event = 'ActionH'

[[button]]
code = 2
event = 'BumperR'

[[button]]
code = 3
event = 'Next'

[[button]]
code = 4
event = 'TriggerL'

[[button]]
code = 5
event = 'TriggerR'

[[button]]
code = 7
event = 'ActionB'

[[button]]
code = 8
event = 'ActionV'

[[button]]
code = 10
event = 'DpadUp'

[[button]]
code = 11
event = 'DpadDown'

[[button]]
code = 12
event = 'DpadLeft'

[[button]]
code = 13
event = 'DpadRight'

[[axis]]
code = 0
event = 'JoyX'

[[axis]]
code = 1
event = 'JoyY'

[[axis]]
code = 3
event = 'CamX'

[[axis]]
code = 4
event = 'CamY'
