name = "Saitek P2500 Force Rumble Pad"
type = "Unknown"

[[button]]
code = 5
event = "BumperR"

[[button]]
code = 4
event = "BumperL"

[[button]]
code = 2
event = "ActionA"

[[button]]
code = 9
event = "CamPush"

[[button]]
code = 7
event = "TriggerR"

[[button]]
code = 6
event = "TriggerL"

[[button]]
code = 11
event = "Prev"

[[button]]
code = 0
event = "ActionH"

[[button]]
code = 1
event = "ActionV"

[[button]]
code = 3
event = "ActionB"

[[button]]
code = 10
event = "Home"

[[button]]
code = 8
event = "JoyPush"

[[axis]]
code = 2
event = "CamY"

[[axis]]
code = 1
event = "JoyY"

[[axis]]
code = 3
event = "CamX"

[[axis]]
code = 0
event = "JoyX"

[[three_way]]
code = 17
neg = "DpadUp"
pos = "DpadDown"

[[three_way]]
code = 16
neg = "DpadLeft"
pos = "DpadRight"
