name = "Thrustmaster Warthog Throttle"
type = "Flight"

[[button]]
code = 1
event = "MicPush"

[[button]]
code = 2
event = "MicUp"

[[button]]
code = 3
event = "MicLeft"

[[button]]
code = 4
event = "MicDown"

[[button]]
code = 5
event = "MicRight"

[[button]]
code = 6
event = "SpeedbrakeForward"

[[button]]
code = 7
event = "SpeedbrakeBackward"

[[button]]
code = 8
event = "BoatForward"

[[button]]
code = 9
event = "BoatBackward"

[[button]]
code = 10
event = "ChinaForward"

[[button]]
code = 11
event = "ChinaBackward"

[[button]]
code = 12
event = "PinkyForward"

[[button]]
code = 13
event = "PinkyBackward"

[[button]]
code = 14
event = "ThrottleButtonL"

[[button]]
code = 15
event = "EngineFuelFlowL"

[[button]]
code = 416
event = "EngineFuelFlowR"

[[button]]
code = 417
event = "EngineLMotor"

[[button]]
code = 418
event = "EngineRMotor"

[[button]]
code = 419
event = "Apu"

[[button]]
code = 420
event = "LandingGearSilence"

[[button]]
code = 421
event = "FlapsUp"

[[button]]
code = 422
event = "FlapsDown"

[[button]]
code = 423
event = "Eac"

[[button]]
code = 424
event = "RadarAltimeter"

[[button]]
code = 425
event = "AutopilotToggle"

[[button]]
code = 426
event = "AutopilotPath"

[[button]]
code = 427
event = "AutopilotAlt"

[[button]]
code = 430
event = "EngineLIgnition"

[[button]]
code = 431
event = "EngineRIgnition"

[[button]]
code = 0
event = "MousePush"

# [[button]]
# code = 256
# event = "MicUp"

# [[button]]
# code = 257
# event = "MicDown"

# [[button]]
# code = 258
# event = "MicLeft"

# [[button]]
# code = 259
# event = "MicRight"

[[trigger]]
code = 0
event = "MouseX"
max = 1024

[[trigger]]
code = 1
event = "MouseY"
max = 1024

[[trigger]]
code = 2
event = "ThrottleR"
max = 16_339
invert = true

[[trigger]]
code = 5
event = "ThrottleL"
max = 16_339
invert = true

[[axis]]
code = 6
event = "Slew"

[[three_way]]
code = 16
neg = "PovLeft"
pos = "PovRight"

[[three_way]]
code = 17
neg = "PovUp"
pos = "PovDown"
