name = 'Microsoft X-Box One pad'
type = 'Unknown'

[[button]]
code = 6
event = 'Prev'

[[button]]
code = 9
event = 'JoyPush'

[[button]]
code = 10
event = 'CamPush'

[[button]]
code = 16
event = 'ActionA'

[[button]]
code = 17
event = 'ActionB'

[[button]]
code = 19
event = 'ActionH'

[[button]]
code = 20
event = 'ActionV'

[[button]]
code = 22
event = 'BumperL'

[[button]]
code = 23
event = 'BumperR'

[[button]]
code = 26
event = 'Home'

[[button]]
code = 27
event = 'Next'

[[axis]]
code = 0
event = 'JoyX'

[[axis]]
code = 1
event = 'JoyY'

[[axis]]
code = 3
event = 'CamX'

[[axis]]
code = 4
event = 'CamY'

[[trigger]]
code = 2
event = 'TriggerL'

[[trigger]]
code = 5
event = 'TriggerR'

[[three_way]]
code = 16
neg = 'DpadLeft'
pos = 'DpadRight'

[[three_way]]
code = 17
neg = 'DpadUp'
pos = 'DpadDown'
