name = 'SteelSeries Stratus Duo'
type = 'Unknown'

[[button]]
code = 0
event = 'ActionA'

[[button]]
code = 1
event = 'ActionB'

[[button]]
code = 3
event = 'ActionH'

[[button]]
code = 4
event = 'ActionV'

[[button]]
code = 6
event = 'BumperL'

[[button]]
code = 7
event = 'BumperR'

[[button]]
code = 10
event = 'Prev'

[[button]]
code = 11
event = 'Next'

[[button]]
code = 13
event = 'JoyPush'

[[button]]
code = 14
event = 'CamPush'

[[button]]
code = 32
event = 'Home'

[[axis]]
code = 0
event = 'JoyX'

[[axis]]
code = 1
event = 'JoyY'

[[axis]]
code = 2
event = 'CamX'

[[axis]]
code = 3
event = 'CamY'

[[trigger]]
code = 4
event = 'TriggerR'

[[trigger]]
code = 5
event = 'TriggerL'

[[three_way]]
code = 16
neg = 'DpadLeft'
pos = 'DpadRight'

[[three_way]]
code = 17
neg = 'DpadUp'
pos = 'DpadDown'
