name = "Nintendo Wii Remote Pro Controller"
type = "Unknown"

[[button]]
code = 15
event = "DpadLeft"

[[button]]
code = 4
event = "BumperL"

[[button]]
code = 8
event = "Prev"

[[button]]
code = 5
event = "BumperR"

[[button]]
code = 10
event = "Home"

[[button]]
code = 7
event = "TriggerR"

[[button]]
code = 9
event = "Next"

[[button]]
code = 3
event = "ActionH"

[[button]]
code = 0
event = "ActionA"

[[button]]
code = 6
event = "TriggerL"

[[button]]
code = 16
event = "DpadRight"

[[button]]
code = 11
event = "JoyPush"

[[button]]
code = 13
event = "DpadUp"

[[button]]
code = 12
event = "CamPush"

[[button]]
code = 1
event = "ActionB"

[[button]]
code = 2
event = "ActionV"

[[button]]
code = 14
event = "DpadDown"

[[axis]]
code = 2
event = "CamX"

[[axis]]
code = 3
event = "CamY"

[[axis]]
code = 0
event = "JoyX"

[[axis]]
code = 1
event = "JoyY"
