name = "Moga 2 HID"
type = "Unknown"

[[button]]
code = 6
event = "Next"

[[button]]
code = 4
event = "BumperL"

[[button]]
code = 3
event = "ActionV"

[[button]]
code = 9
event = "Prev"

[[button]]
code = 5
event = "BumperR"

[[button]]
code = 1
event = "ActionB"

[[button]]
code = 0
event = "ActionA"

[[button]]
code = 7
event = "JoyPush"

[[button]]
code = 2
event = "ActionH"

[[button]]
code = 8
event = "PovPush"

[[axis]]
code = 1
event = "JoyY"

[[axis]]
code = 2
event = "PovX"

[[axis]]
code = 3
event = "PovY"

[[axis]]
code = 0
event = "JoyX"

[[trigger]]
code = 5
event = "TriggerL"

[[trigger]]
code = 4
event = "TriggerR"

[[three_way]]
code = 17
neg = "DpadUp"
pos = "DpadDown"

[[three_way]]
code = 16
neg = "DpadLeft"
pos = "DpadRight"
