name = "Moga Pro"
type = "Unknown"

[[button]]
code = 0
event = "ActionA"

[[button]]
code = 1
event = "ActionB"

[[button]]
code = 2
event = "ActionH"

[[button]]
code = 3
event = "ActionV"

[[button]]
code = 4
event = "BumperL"

[[button]]
code = 5
event = "BumperR"

[[button]]
code = 6
event = "Next"

[[button]]
code = 7
event = "JoyPush"

[[button]]
code = 8
event = "CamPush"

[[axis]]
code = 0
event = "JoyX"

[[axis]]
code = 1
event = "JoyY"

[[axis]]
code = 2
event = "CamX"

[[axis]]
code = 3
event = "CamY"

[[trigger]]
code = 4
event = "TriggerR"

[[trigger]]
code = 5
event = "TriggerL"

[[three_way]]
code = 16
neg = "DpadLeft"
pos = "DpadRight"

[[three_way]]
code = 17
neg = "DpadUp"
pos = "DpadDown"
