name = "Joy-Con (R)"
type = "Unknown"

[[button]]
code = 12
event = "Prev"

[[button]]
code = 4
event = "BumperL"

[[button]]
code = 0
event = "ActionA"

[[button]]
code = 11
event = "JoyPush"

[[button]]
code = 2
event = "ActionH"

[[button]]
code = 3
event = "ActionV"

[[button]]
code = 5
event = "BumperR"

[[button]]
code = 9
event = "Next"

[[button]]
code = 1
event = "ActionB"

[[axis]]
code = 17
event = "JoyY"

[[axis]]
code = 16
event = "JoyX"
