name = 'Mad Catz R.A.T. Pro X mouse'
type = 'MOUSE'

[[button]]
code = 1
event = 'MouseMenu'

[[button]]
code = 2
event = 'WheelPush'

[[button]]
code = 3
event = 'Prev'

[[button]]
code = 4
event = 'Next'

[[button]]
code = 5
event = 'BumperL'

[[button]]
code = 6
event = 'Dpi'

[[axis]]
code = 0
event = 'MouseX'

[[axis]]
code = 1
event = 'MouseY'

[[axis]]
code = 5
event = 'WheelX'
