AutopilotToggle = "Autopilot Engage/Disengage Button"
LandingGearSilence = "L/G WRN Silence Button"
ThrottleButtonL = "Left Throttle Button"
Eac = "EAC Switch"
RadarAltimeter = "Radar Altimeter Switch"
Apu = "APU Start Switch"
EngineFuelFlowL = "Left Engine Fuel Flow Switch"
EngineFuelFlowR = "Right Engine Fuel Flow Switch"
AutopilotSelect = "Autopilot Select Switch"
Flaps = "Flaps Switch"
EngineOperateL = "Left Engine Operate Switch"
EngineOperateR = "Right Engine Operate Switch"
PinkySwitch = "Pinky Switch"
Speedbrake = "Speedbrake Switch"
BoatSwitch = "Boat Switch"
ChinaHat = "China Hat"
Pov = "POV Hat"
Mic = "Mic Switch"
Slew = "Slew Dial"
ThrottleL = "Left Throttle"
ThrottleR = "Right Throttle"
