name = "Thrustmaster Flightstick"
type = "Thrustmaster"

[[button]]
code = 0
event = "ActionA"

[[button]]
code = 1
event = "ActionV"

[[button]]
code = 2
event = "ActionB"

[[button]]
code = 3
event = "ActionH"

[[axis]]
code = 0
event = "JoyX"

[[axis]]
code = 1
event = "JoyY"

[[axis]]
code = 2
event = "Throttle"
max = -1.0

[[three_way]]
code = 16
neg = "PovLeft"
pos = "PovRight"

[[three_way]]
code = 17
neg = "PovUp"
pos = "PovDown"
