# "stick" Source Code - Licensed under the MIT LICENSE (see /LICENSE)

[package]
name = "typer"
version = "0.1.0"
authors = ["Jeron A. Lau <jeron.lau@plopgrizzly.com>"]

[dependencies]
stick = { path = "../../" }
termion = "1.5.1"
