name = "Mayflash GameCube Controller"
type = "Unknown"

[[button]]
code = 2
event = "ActionB"

[[button]]
code = 1
event = "ActionA"

[[button]]
code = 9
event = "Next"

[[button]]
code = 14
event = "DpadDown"

[[button]]
code = 7
event = "BumperR"

[[button]]
code = 15
event = "DpadLeft"

[[button]]
code = 3
event = "ActionV"

[[button]]
code = 0
event = "ActionH"

[[button]]
code = 13
event = "DpadRight"

[[button]]
code = 12
event = "DpadUp"

[[axis]]
code = 0
event = "JoyX"

[[axis]]
code = 2
event = "PovY"

[[axis]]
code = 1
event = "JoyY"

[[axis]]
code = 5
event = "PovX"

[[trigger]]
code = 4
event = "TriggerR"

[[trigger]]
code = 3
event = "TriggerL"
