name = "USB Gamepad1"
type = "Unknown"

[[button]]
code = 8
event = "Prev"

[[button]]
code = 1
event = "ActionB"

[[button]]
code = 9
event = "Next"

[[button]]
code = 2
event = "ActionA"

[[axis]]
code = 4
event = "DpadUp"

[[axis]]
code = 1
event = "DpadLeft"

[[axis]]
code = 0
event = "DpadDown"

[[axis]]
code = 2
event = "DpadRight"
