name = "HORI CO. LTD. REAL ARCADE Pro.V3"
type = "Unknown"

[[button]]
code = 1
event = "ActionA"

[[button]]
code = 7
event = "TriggerR"

[[button]]
code = 0
event = "ActionH"

[[button]]
code = 8
event = "Prev"

[[button]]
code = 4
event = "BumperL"

[[button]]
code = 6
event = "TriggerL"

[[button]]
code = 2
event = "ActionB"

[[button]]
code = 12
event = "Cmd"

[[button]]
code = 3
event = "ActionV"

[[button]]
code = 5
event = "BumperR"

[[button]]
code = 9
event = "Next"

[[three_way]]
code = 17
neg = "DpadUp"
pos = "DpadDown"

[[three_way]]
code = 16
neg = "DpadLeft"
pos = "DpadRight"
