name = "Microsoft SideWinder"
type = "Unknown"

[[button]]
code = 4
event = "ActionV"

[[button]]
code = 0
event = "ActionA"

[[button]]
code = 1
event = "ActionB"

[[button]]
code = 8
event = "Next"

[[button]]
code = 3
event = "ActionH"

[[button]]
code = 9
event = "Prev"

[[button]]
code = 7
event = "BumperR"

[[button]]
code = 6
event = "BumperL"

[[three_way]]
code = 17
neg = "DpadUp"
pos = "DpadDown"

[[three_way]]
code = 16
neg = "DpadLeft"
pos = "DpadRight"
