name = "Hori Real Arcade Pro.EX-SE (Xbox 360)"
type = "Unknown"

[[button]]
code = 10
event = "Home"

[[button]]
code = 2
event = "ActionH"

[[button]]
code = 0
event = "ActionA"

[[button]]
code = 7
event = "TriggerR"

[[button]]
code = 9
event = "Next"

[[button]]
code = 8
event = "Prev"

[[button]]
code = 5
event = "BumperR"

[[button]]
code = 1
event = "ActionB"

[[button]]
code = 4
event = "BumperL"

[[button]]
code = 3
event = "ActionV"

[[button]]
code = 6
event = "TriggerL"

[[three_way]]
code = 17
neg = "DpadUp"
pos = "DpadDown"

[[three_way]]
code = 16
neg = "DpadLeft"
pos = "DpadRight"
