name = "Thrustmaster Warthog Throttle"

[button.AutopilotToggle]
name = "Autopilot Engage/Disengage Button"
code = 713

[button.LandingGearSilence]
name = "L/G WRN Silence Button"
code = 708

[button.ThrottleButtonL]
name = "Left Throttle Button"
code = 302

[two_way.Eac]
name = "EAC Switch"
code = 711

[two_way.RadarAltimeter]
name = "Radar Altimeter Switch"
code = 712

[two_way.Apu]
name = "APU Start Switch"
code = 707

[two_way.EngineLeft]
name = "Left Engine Operate Switch"
code = 303

[two_way.EngineRight]
name = "Right Engine Operate Switch"
code = 704

[three_way.AltitudeHeading]
name = "Altitude Heading Switch"
forward = 714
backward = 715

[three_way.Maneuver]
name = "Maneuver Switch"
forward = 709
backward = 710

[three_way.IgnitionL]
name = "Left Ignition Switch"
forward = 718
backward = 705

[three_way.IgnitionR]
name = "Right Ignition Switch"
forward = 719
backward = 706

[three_way.PinkySwitch]
name = "Pinky Switch"
forward = 300
backward = 301

[three_way.Speedbrake]
name = "Speedbrake Switch"
forward = 294
backward = 295

[three_way.BoatSwitch]
name = "Boat Switch"
forward = 296
backward = 297

[three_way.ChinaHat]
neutral = "China Hat"
forward = 298
backward = 299

[dir.dpad_hat]
name = "POV Hat"
[dir.dpad_hat.axes]
x = 0
y = 1

[dir.mic_hat]
name = "Mic Switch"
[dir.mic_hat.buttons]
up = 544
down = 545
left = 546
right = 547

[axis.Slew]
name = "Slew Dial"
code = 6

[axis.ThrottleL]
name = "Left Throttle"
code = 5

[axis.ThrottleR]
name = "Right Throttle"
code = 2
