name = "Thrustmaster Warthog Throttle"
type = "HOTAS"

[[button]]
code = 425
event = "AutopilotToggle"

[[button]]
code = 420
event = "LandingGearSilence"

[[button]]
code = 14
event = "ThrottleButtonL"

[[button]]
code = 423
event = "Eac"

[[button]]
code = 424
event = "RadarAltimeter"

# Two way switches (buttons in evdev)
[[button]]
code = 419
event = "Apu"

[[button]]
code = 15
event = "EngineFuelFlowL"

[[button]]
code = 416
event = "EngineFuelFlowR"

[[button]]
code = 426
event = "AutopilotSelectPath"

[[button]]
code = 427
event = "AutopilotSelectAlt"

[[button]]
code = 421
event = "FlapsUp"

[[button]]
code = 422
event = "FlapsDown"

[[button]]
code = 430
event = "EngineOperateLIgnition"

[[button]]
code = 417
event = "EngineOperateLMotor"

[[button]]
code = 431
event = "EngineOperateRIgnition"

[[button]]
code = 418
event = "EngineOperateRMotor"

[[button]]
code = 12
event = "PinkyForward"

[[button]]
code = 13
event = "PinkyBackward"

[[button]]
code = 6
event = "SpeedbrakeForward"

[[button]]
code = 7
event = "SpeedbrakeBackward"

[[button]]
code = 8
event = "BoatForward"

[[button]]
code = 9
event = "BoatBackward"

[[button]]
code = 10
event = "ChinaForward"

[[button]]
code = 11
event = "ChinaBackward"

[[button]]
code = 256
event = "MicUp"

[[button]]
code = 257
event = "MicDown"

[[button]]
code = 258
event = "MicLeft"

[[button]]
code = 259
event = "MicRight"

[[axis]]
code = 6
name = "Slew"

[[axis]]
code = 5
event = "ThrottleL"

[[axis]]
code = 2
event = "ThrottleR"

[[three_way]]
code = 0
neg = "PovLeft"
pos = "PovRight"

[[three_way]]
code = 1
neg = "PovUp"
pos = "PovDown"
